package com.mega.mvc06;

import java.io.FileWriter;
import java.io.IOException;

public class 예외처리발생5main {

	public static void main(String[] args) {
		
		예외처리발생5 error = new 예외처리발생5();
		error.call();
		System.out.println("에러 발생후 실행될까요");
		System.out.println("에러 발생후 실행될까요");
		System.out.println("에러 발생후 실행될까요");
		System.out.println("에러 발생후 실행될까요");
		System.out.println("에러 발생후 실행될까요");
		System.out.println("에러 발생후 실행될까요");
		
	}
}